[package]
name = "e2e"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.53.1", features = ["rt-multi-thread", "time"] }
google-cloud-pubsub = "0.33.2"
google-cloud-googleapis = "0.16.1"
prost-types = "0.14.4"
tokio-util = "0.7.19"
anyhow = "1.0.104"
futures-util = "0.3.34"